# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: How to get Help
author: Safer Community of Fulbright Wellness Center and Fulbright Student Council
logo: logo.png
copyright: "2023"
only_build_toc_files: true
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
execute:
  execute_notebooks: "auto"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/panda1835/fulbright-how-to-get-help  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  favicon: "./favicon.ico"
  # comments:
  #   hypothesis: true